# /*
# * Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# *
# * Permission is hereby granted, free of charge, to any person obtaining a copy of this
# * software and associated documentation files (the "Software"), to deal in the Software
# * without restriction, including without limitation the rights to use, copy, modify,
# * merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# * permit persons to whom the Software is furnished to do so.
# *
# * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
# */

AWSTemplateFormatVersion: "2010-09-09"
Description: React Amplify 101 Lab (L200)

Parameters:
  EC2InstanceType:
    Description: EC2 instance type on which IDE runs
    Type: String
    Default: m5.large
    AllowedValues:
      - m5.large

  AutoHibernateTimeout:
    Description: How many minutes idle before shutting down the IDE. Options, 30min, 1hr, 4hr, 1day, 1week, Never (0)
    Type: Number
    Default: 30
    AllowedValues:
      - 30
      - 60
      - 240
      - 1440
      - 10080
      - 0

  Env:
    Description: Please specify the target Env. Used for tagging and resource names. Mandatory LOWER CASE.
    Type: String
    Default: "poc"
    AllowedValues:
      - poc
      - dev
      - prod

Resources:
  C9IDE:
    Type: "AWS::Cloud9::EnvironmentEC2"
    Properties:
      Name: !Sub "AWSAmplifyReact101-Cloud9-IDE"
      Description: !Sub "AWSAmplifyReact101 Cloud9 IDE"
      AutomaticStopTimeMinutes: !Ref "AutoHibernateTimeout"
      InstanceType: !Ref "EC2InstanceType"

  CFNUser:
    Type: AWS::IAM::User
  CFNUserPolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: CFNUser
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              [
                "cloudformation:*",
                "iam:*",
                "appsync:*",
                "amplify:*",
                "apigateway:*",
                "cognito-idp:*",
                "cognito-identity:*",
                "s3:*",
              ]
            Resource: "*"
      Users: [!Ref "CFNUser"]
  CFNKeys:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref "CFNUser"
Outputs:
  AccessKey:
    Value: !Ref "CFNKeys"
    Description: AWSAccessKeyId of new user
  SecretKey:
    Value: !GetAtt [CFNKeys, SecretAccessKey]
    Description: AWSSecretAccessKey of the new user
  Cloud9URL:
    Description: Cloud9 Environment
    Value:
      Fn::Join:
        - ""
        - - !Sub https://${AWS::Region}.console.aws.amazon.com/cloud9/ide/
          - !Ref "C9IDE"
